// sidebarsIntroduction.js
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  introductionSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;